jobs:
  - job: Ruby_mingw
    timeoutInMinutes: 60
    pool:
      vmImage: vs2015-win2012r2
    strategy:
      maxParallel: 5
      matrix:
        x64-mingw32:
          platform: x64
    steps:
      - checkout: self
        fetchDepth: 10

      - powershell: ./azure_pipeline_prereqs.ps1
        displayName: $(System.JobName) install prerequisites

      - powershell: |
          git config --global core.autocrlf false
          git clone -q --depth=5 --no-tags --branch=master https://github.com/oneclick/rubyinstaller2.git    ./rubyinstaller2
          git clone -q --depth=5 --no-tags --branch=master https://github.com/ConnorAtherton/rb-readline.git ./ruby_readline
          git clone -q --depth=5 --no-tags --branch=trunk  https://github.com/ruby/ruby.git                  ./ruby
        displayName: $(System.JobName) install ruby, ri2, rb-readline

      - powershell: $env:path = "D:\ruby\bin;$env:path" ; ./1_0_build_install_64.ps1
        failOnStderr: false
        displayName: $(System.JobName) config, build, and install

      - powershell: |
          $env:path = "$env:BUILD_SOURCESDIRECTORY\install\bin;$env:path"
          ruby.exe azure_install_info.rb
        continueOnError: true
        displayName: $(System.JobName) install info
        
      - powershell: $env:path = ./2_0_test.ps1
        failOnStderr: false
        continueOnError: true
        displayName: $(System.JobName) test

      - task: PublishBuildArtifacts@1
        displayName: Publish logs
        continueOnError: true
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/logs
          artifactName: mingw-logs
